//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orcus.Administration.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orcus.Administration.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                  Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Apache2_0 {
            get {
                return ResourceManager.GetString("Apache2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD 3-Clause License
        ///
        ///{0}
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///* Redistributions of source code must retain the above copyright notice, this
        ///  list of conditions and the following disclaimer.
        ///
        ///* Redistributions in binary form must reproduce the above copyright notice,
        ///  this list of conditions and the following disclaimer in the documentation
        ///  and/or other materials  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSD3 {
            get {
                return ResourceManager.GetString("BSD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE (&quot;CCPL&quot; OR &quot;LICENSE&quot;). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
        ///
        ///BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CC3 {
            get {
                return ResourceManager.GetString("CC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE (&quot;CCPL&quot; OR &quot;LICENSE&quot;). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
        ///
        ///BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CC3SA {
            get {
                return ResourceManager.GetString("CC3SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble
        ///This License governs Your use of the Work. This License is intended to allow developers to use the Source Code and Executable Files provided as part of the Work in any application in any form.
        ///
        ///The main points subject to the terms of the License are:
        ///
        ///Source Code and Executable Files can be used in commercial applications;
        ///Source Code and Executable Files can be redistributed; and
        ///Source Code can be modified to create derivative works.
        ///No claim of suitability, guarantee, or any warranty wha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPOL {
            get {
                return ResourceManager.GetString("CPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                    GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///
        ///  This version of the GNU Lesser General Public License incorporates
        ///the terms and conditions of version 3 of the GNU General Public
        ///License, supplemented by the additional permissions listed below.
        ///
        ///  0. Ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGPL {
            get {
                return ResourceManager.GetString("LGPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New BSD License (BSD)
        ///Copyright (c) 2010, Roman Atachiants (kelindar@gmail.com)
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///
        ///* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LZF_License {
            get {
                return ResourceManager.GetString("LZF_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///{0}
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIT {
            get {
                return ResourceManager.GetString("MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                           MOZILLA PUBLIC LICENSE
        ///                                Version 1.1
        ///
        ///                              ---------------
        ///
        ///1. Definitions.
        ///
        ///     1.0.1. &quot;Commercial Use&quot; means distribution or otherwise making the
        ///     Covered Code available to a third party.
        ///
        ///     1.1. &quot;Contributor&quot; means each entity that creates or contributes to
        ///     the creation of Modifications.
        ///
        ///     1.2. &quot;Contributor Version&quot; means the combination of the Original
        ///     Code, prior Modifications used by a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MPL1_1 {
            get {
                return ResourceManager.GetString("MPL1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Public License
        ///Version 2.0
        ///
        ///1. Definitions
        ///
        ///1.1. “Contributor”
        ///means each individual or legal entity that creates, contributes to the creation of, or owns Covered Software.
        ///
        ///1.2. “Contributor Version”
        ///means the combination of the Contributions of others (if any) used by a Contributor and that particular Contributor’s Contribution.
        ///
        ///1.3. “Contribution”
        ///means Covered Software of a particular Contributor.
        ///
        ///1.4. “Covered Software”
        ///means Source Code Form to which the initial Contributor ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MPL2 {
            get {
                return ResourceManager.GetString("MPL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (MS-PL)
        ///This license governs use of the accompanying software. If you use the software, you
        ///accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the
        ///same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person that distributes its contribution under [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_PL {
            get {
                return ResourceManager.GetString("MS_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License agreement for Ookii.Dialogs.
        ///
        ///Copyright © Sven Groot (Ookii.org) 2009
        ///All rights reserved.
        ///
        ///
        ///Redistribution and use in source and binary forms, with or without 
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///1) Redistributions of source code must retain the above copyright notice, 
        ///   this list of conditions and the following disclaimer. 
        ///2) Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ookii_Dialogs {
            get {
                return ResourceManager.GetString("Ookii_Dialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Terms of Service is a legal contract between you and Orcus Technologies GP (“Orcus Technologies GP“, “we“, “our“), governing your use of software or web services or mobile or web software (“ Orcus Technologies GP Software ”) owned, controlled or offered by Orcus Technologies GP (collectively, the ”Orcus Technologies GP Software“). PLEASE READ CAREFULLY THE FOLLOWING TERMS AND CONDITIONS OF SERVICE. BY USING ORCUS TECHNOLOGIES GP SOFTWARE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD AND AGREE TO BE B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrcusEULA {
            get {
                return ResourceManager.GetString("OrcusEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT VISUAL STUDIO 2015 IMAGE LIBRARY
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. They apply to the software named above. The terms also apply to any Microsoft services or updates for the software, except to the extent those have different terms.
        ///IF YOU COMPLY WITH THESE LICENSE TERMS, YOU HAVE THE RIGHTS BELOW.
        ///1. INSTALLATION AND USE RIGHTS. 
        ///a. One user may use copies of the soft [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Visual_Studio_2015_Image_Library_EULA {
            get {
                return ResourceManager.GetString("Visual_Studio_2015_Image_Library_EULA", resourceCulture);
            }
        }
    }
}
