namespace Orcus.Native
{
    public enum DiFunction
    {
        SelectDevice = 1,
        InstallDevice = 2,
        AssignResources = 3,
        Properties = 4,
        Remove = 5,
        FirstTimeSetup = 6,
        FoundDevice = 7,
        SelectClassDrivers = 8,
        ValidateClassDrivers = 9,
        InstallClassDrivers = 0xa,
        CalcDiskSpace = 0xb,
        DestroyPrivateData = 0xc,
        ValidateDriver = 0xd,
        Detect = 0xf,
        InstallWizard = 0x10,
        DestroyWizardData = 0x11,
        PropertyChange = 0x12,
        EnableClass = 0x13,
        DetectVerify = 0x14,
        InstallDeviceFiles = 0x15,
        UnRemove = 0x16,
        SelectBestCompatDrv = 0x17,
        AllowInstall = 0x18,
        RegisterDevice = 0x19,
        NewDeviceWizardPreSelect = 0x1a,
        NewDeviceWizardSelect = 0x1b,
        NewDeviceWizardPreAnalyze = 0x1c,
        NewDeviceWizardPostAnalyze = 0x1d,
        NewDeviceWizardFinishInstall = 0x1e,
        Unused1 = 0x1f,
        InstallInterfaces = 0x20,
        DetectCancel = 0x21,
        RegisterCoInstallers = 0x22,
        AddPropertyPageAdvanced = 0x23,
        AddPropertyPageBasic = 0x24,
        Reserved1 = 0x25,
        Troubleshooter = 0x26,
        PowerMessageWake = 0x27,
        AddRemotePropertyPageAdvanced = 0x28,
        UpdateDriverUI = 0x29,
        Reserved2 = 0x30
    }
}