//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orcus.StaticCommands.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orcus.StaticCommands.Resources.StaticCommands", typeof(StaticCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments the file should be executed with.
        /// </summary>
        internal static string ArgumentsDescription {
            get {
                return ResourceManager.GetString("ArgumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminates the client process and don&apos;t let it respawn.
        /// </summary>
        internal static string Client_KillCommand_Description {
            get {
                return ResourceManager.GetString("Client_KillCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Client_KillCommand_Name {
            get {
                return ResourceManager.GetString("Client_KillCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to restart the client process with elevated privileges. If that fails, the client continues running with user permissions.
        /// </summary>
        internal static string Client_MakeAdminCommand_Description {
            get {
                return ResourceManager.GetString("Client_MakeAdminCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Administrator Privileges.
        /// </summary>
        internal static string Client_MakeAdminCommand_Name {
            get {
                return ResourceManager.GetString("Client_MakeAdminCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover passwords and cookies on the client&apos;s pc.
        /// </summary>
        internal static string Client_PasswordRecoveryCommand_Description {
            get {
                return ResourceManager.GetString("Client_PasswordRecoveryCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string Client_PasswordRecoveryCommand_Name {
            get {
                return ResourceManager.GetString("Client_PasswordRecoveryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force the client to send the current key log.
        /// </summary>
        internal static string Client_RequestKeyLogCommand_Description {
            get {
                return ResourceManager.GetString("Client_RequestKeyLogCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Key Log.
        /// </summary>
        internal static string Client_RequestKeyLogCommand_Name {
            get {
                return ResourceManager.GetString("Client_RequestKeyLogCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the client, remove all dependencies and remove all files.
        /// </summary>
        internal static string Client_UninstallCommand_Description {
            get {
                return ResourceManager.GetString("Client_UninstallCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Client_UninstallCommand_Name {
            get {
                return ResourceManager.GetString("Client_UninstallCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the current client, execute the new file and terminate the client.
        /// </summary>
        internal static string Client_UpdateCommand_Description {
            get {
                return ResourceManager.GetString("Client_UpdateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Client_UpdateCommand_Name {
            get {
                return ResourceManager.GetString("Client_UpdateCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable the file should be updated with.
        /// </summary>
        internal static string Client_UpdateCommand_PathDescription {
            get {
                return ResourceManager.GetString("Client_UpdateCommand_PathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the file from the url, uninstall the current client, execute the new file and terminate the client.
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_Description {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL.
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_DownloadUrl {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The http(s) url of the file which should be downloaded.
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_DownloadUrl_Description {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_DownloadUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Hash.
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_FileHash {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SHA256 hash value of the file. Leave empty if no hash comparison is required..
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_FileHash_Description {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_FileHash_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (Url).
        /// </summary>
        internal static string Client_UpdateFromUrlCommand_Name {
            get {
                return ResourceManager.GetString("Client_UpdateFromUrlCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send magic packets to the clients to wake them up. Only works if the clients are in the same network like the server..
        /// </summary>
        internal static string Computer_WakeOnLanCommand_Description {
            get {
                return ResourceManager.GetString("Computer_WakeOnLanCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake On Lan.
        /// </summary>
        internal static string Computer_WakeOnLanCommand_Name {
            get {
                return ResourceManager.GetString("Computer_WakeOnLanCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files|*.exe.
        /// </summary>
        internal static string ExecutableFilesFilter {
            get {
                return ResourceManager.GetString("ExecutableFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Check.
        /// </summary>
        internal static string FileCheck {
            get {
                return ResourceManager.GetString("FileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the given text in Notepad so the user can read and copy it..
        /// </summary>
        internal static string Interaction_OpenTextInNotepadCommand_Description {
            get {
                return ResourceManager.GetString("Interaction_OpenTextInNotepadCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Text in Notepad.
        /// </summary>
        internal static string Interaction_OpenTextInNotepadCommand_Name {
            get {
                return ResourceManager.GetString("Interaction_OpenTextInNotepadCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text displayed in notepad..
        /// </summary>
        internal static string Interaction_OpenTextInNotepadCommand_Text_Description {
            get {
                return ResourceManager.GetString("Interaction_OpenTextInNotepadCommand_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the window of notepad..
        /// </summary>
        internal static string Interaction_OpenTextInNotepadCommand_Title_Description {
            get {
                return ResourceManager.GetString("Interaction_OpenTextInNotepadCommand_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a simple balloon tooltip message.
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the icon for the balloon tooltip..
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Icon_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Icon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Balloon Tooltip.
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Name {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to display on the balloon tooltip..
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Text_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time period, in milliseconds, the balloon tip should display..
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Timeout_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title to display on the balloon tooltip..
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_Title_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text cannot be empty.
        /// </summary>
        internal static string Interaction_ShowBalloonTooltipCommand_ValidateInput_TextCannotBeEmpty {
            get {
                return ResourceManager.GetString("Interaction_ShowBalloonTooltipCommand_ValidateInput_TextCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Buttons {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which buttons to display in the message box..
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Buttons_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Buttons_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Button.
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_DefaultButton {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the default button for the message box..
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_DefaultButton_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_DefaultButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a message box. The button which was pressed by the user will be returned.
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which icon to display in the message box..
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Icon_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Icon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Message Box.
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Name {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to display in the message box..
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Text_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to display in the title bar of the message box..
        /// </summary>
        internal static string Interaction_ShowMessageBoxCommand_Title_Description {
            get {
                return ResourceManager.GetString("Interaction_ShowMessageBoxCommand_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        internal static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash value. Please make sure that you use a SHA256 hash formatted as hexadecimal (64 chars).
        /// </summary>
        internal static string InvalidSHA256HashValueHex {
            get {
                return ResourceManager.GetString("InvalidSHA256HashValueHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path cannot be empty.
        /// </summary>
        internal static string PathCannotBeEmpty {
            get {
                return ResourceManager.GetString("PathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        internal static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text cannot be empty.
        /// </summary>
        internal static string ShowMessageBoxCommand_ValidateInput_TextCannotBeEmpty {
            get {
                return ResourceManager.GetString("ShowMessageBoxCommand_ValidateInput_TextCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer State.
        /// </summary>
        internal static string System_ChangeComputerStateCommand_ComputerState {
            get {
                return ResourceManager.GetString("System_ChangeComputerStateCommand_ComputerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action which should be done.
        /// </summary>
        internal static string System_ChangeComputerStateCommand_ComputerState_Description {
            get {
                return ResourceManager.GetString("System_ChangeComputerStateCommand_ComputerState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown, restart or log off the computer.
        /// </summary>
        internal static string System_ChangeComputerStateCommand_Description {
            get {
                return ResourceManager.GetString("System_ChangeComputerStateCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Computer State.
        /// </summary>
        internal static string System_ChangeComputerStateCommand_Name {
            get {
                return ResourceManager.GetString("System_ChangeComputerStateCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the desktop wallpaper of the computer to an image from a url.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_Description {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Desktop Wallpaper.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_Name {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wallpaper url cannot be empty.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_ValidateInput_WallpaperUrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_ValidateInput_WallpaperUrlCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Style.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_WallpaperStyle {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_WallpaperStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the desktop bitmap is displayed on the desktop.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_WallpaperStyle_Description {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_WallpaperStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper URL.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_WallpaperUrl {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_WallpaperUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The http url to the wallpaper.
        /// </summary>
        internal static string System_ChangeWallpaperCommand_WallpaperUrl_Description {
            get {
                return ResourceManager.GetString("System_ChangeWallpaperCommand_WallpaperUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the given file from the Orcus Server and execute it.
        /// </summary>
        internal static string System_DownloadAndExecuteCommand_Description {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute using Service.
        /// </summary>
        internal static string System_DownloadAndExecuteCommand_ExecuteUsingService {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteCommand_ExecuteUsingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the file using the Orcus Service if it is available.
        /// </summary>
        internal static string System_DownloadAndExecuteCommand_ExecuteUsingService_Description {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteCommand_ExecuteUsingService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Execute.
        /// </summary>
        internal static string System_DownloadAndExecuteCommand_Name {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file which should be executed on the remote system.
        /// </summary>
        internal static string System_DownloadAndExecuteCommand_Path_Description {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteCommand_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a file from an url and execute it.
        /// </summary>
        internal static string System_DownloadAndExecuteFromUrlCommand_Description {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteFromUrlCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Execute from Url.
        /// </summary>
        internal static string System_DownloadAndExecuteFromUrlCommand_Name {
            get {
                return ResourceManager.GetString("System_DownloadAndExecuteFromUrlCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string System_ExecuteProcessCommand_Administrator {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the process with administrator privileges. This won&apos;t have an effect if the verb is set..
        /// </summary>
        internal static string System_ExecuteProcessCommand_Administrator_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Administrator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command-line arguments to use when starting the application.
        /// </summary>
        internal static string System_ExecuteProcessCommand_Arguments_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Arguments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create No Window.
        /// </summary>
        internal static string System_ExecuteProcessCommand_CreateNoWindow {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_CreateNoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the process without creating a new window. Only affects console..
        /// </summary>
        internal static string System_ExecuteProcessCommand_CreateNoWindow_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_CreateNoWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the file of the given file path..
        /// </summary>
        internal static string System_ExecuteProcessCommand_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application to start.
        /// </summary>
        internal static string System_ExecuteProcessCommand_FileName_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute file.
        /// </summary>
        internal static string System_ExecuteProcessCommand_Name {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Execute.
        /// </summary>
        internal static string System_ExecuteProcessCommand_ShellExecute {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_ShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the operating system shell to start the process..
        /// </summary>
        internal static string System_ExecuteProcessCommand_ShellExecute_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_ShellExecute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verb does not seem to be available on this computer. Do you want to continue?.
        /// </summary>
        internal static string System_ExecuteProcessCommand_ValidateInput_VerbDoesNotExist {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_ValidateInput_VerbDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb.
        /// </summary>
        internal static string System_ExecuteProcessCommand_Verb {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verb to use when opening the file.
        /// </summary>
        internal static string System_ExecuteProcessCommand_Verb_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_Verb_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Style.
        /// </summary>
        internal static string System_ExecuteProcessCommand_WindowStyle {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_WindowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window style the application should adapt to..
        /// </summary>
        internal static string System_ExecuteProcessCommand_WindowStyle_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_WindowStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        internal static string System_ExecuteProcessCommand_WorkingDirectory {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory for the process. That has no effect if Shell Execute is true.
        /// </summary>
        internal static string System_ExecuteProcessCommand_WorkingDirectory_Description {
            get {
                return ResourceManager.GetString("System_ExecuteProcessCommand_WorkingDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string System_OpenWebsiteCommand_Amount {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of website instances.
        /// </summary>
        internal static string System_OpenWebsiteCommand_Amount_Description {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_Amount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a website x times on the computer.
        /// </summary>
        internal static string System_OpenWebsiteCommand_Description {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Website.
        /// </summary>
        internal static string System_OpenWebsiteCommand_Name {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid url. Open anyway?.
        /// </summary>
        internal static string System_OpenWebsiteCommand_ValidateInput_InvalidUrl {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_ValidateInput_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a positive not zero value for the Times property.
        /// </summary>
        internal static string System_OpenWebsiteCommand_ValidateInput_Times {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_ValidateInput_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        internal static string System_OpenWebsiteCommand_WebsiteUrl {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_WebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url to the website.
        /// </summary>
        internal static string System_OpenWebsiteCommand_WebsiteUrl_Description {
            get {
                return ResourceManager.GetString("System_OpenWebsiteCommand_WebsiteUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string System_SystemLockCommand_Background {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the lock screen background..
        /// </summary>
        internal static string System_SystemLockCommand_Background_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Background_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows.
        /// </summary>
        internal static string System_SystemLockCommand_CloseWindows {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_CloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constantly close other windows on the new desktop. That won&apos;t affect any windows the user did open in the default desktop..
        /// </summary>
        internal static string System_SystemLockCommand_CloseWindows_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_CloseWindows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the computer system and prevent any user interation until the command is stopped.
        /// </summary>
        internal static string System_SystemLockCommand_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Desktop.
        /// </summary>
        internal static string System_SystemLockCommand_DifferentDesktop {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DifferentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new desktop and set it as the default desktop. The original desktop will be restored when the command is stopped..
        /// </summary>
        internal static string System_SystemLockCommand_DifferentDesktop_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DifferentDesktop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Task Manager.
        /// </summary>
        internal static string System_SystemLockCommand_DisableTaskManager {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DisableTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the Windows Task Manager to prevent the user from killing the process. This feature requires administrator privileges..
        /// </summary>
        internal static string System_SystemLockCommand_DisableTaskManager_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DisableTaskManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable user input.
        /// </summary>
        internal static string System_SystemLockCommand_DisableUserInput {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DisableUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the mouse and keyboard. This feature requires administrator privileges..
        /// </summary>
        internal static string System_SystemLockCommand_DisableUserInput_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_DisableUserInput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string System_SystemLockCommand_Message {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a message.
        /// </summary>
        internal static string System_SystemLockCommand_Message_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock System.
        /// </summary>
        internal static string System_SystemLockCommand_Name {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically bring to front.
        /// </summary>
        internal static string System_SystemLockCommand_PeriodicallySetTopWindow {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_PeriodicallySetTopWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may be possible that the window will be overlapped by other topmost windows. This option prevents that..
        /// </summary>
        internal static string System_SystemLockCommand_PeriodicallySetTopWindow_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_PeriodicallySetTopWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Closing.
        /// </summary>
        internal static string System_SystemLockCommand_PreventClosing {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_PreventClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent the key combination Alt+F4 and the close button in the taskbar..
        /// </summary>
        internal static string System_SystemLockCommand_PreventClosing_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_PreventClosing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Screen.
        /// </summary>
        internal static string System_SystemLockCommand_RotateScreen {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_RotateScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the screen to make it difficult for the user to navigate. The screen will be restored when the command is stopped..
        /// </summary>
        internal static string System_SystemLockCommand_RotateScreen_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_RotateScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost.
        /// </summary>
        internal static string System_SystemLockCommand_Topmost {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the window overlapping other windows..
        /// </summary>
        internal static string System_SystemLockCommand_Topmost_Description {
            get {
                return ResourceManager.GetString("System_SystemLockCommand_Topmost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string TheFileDoesnotExist {
            get {
                return ResourceManager.GetString("TheFileDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die URL darf nicht leer sein.
        /// </summary>
        internal static string UrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("UrlCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtbarkeit.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei {0} hat eine Dateigröße über 5 MiB. Bitte beachten Sie, dass diese Datei in den Arbeitsspeicher geladen und an jeden Client übertragen werden muss, was lange dauern kann, wenn dies eine große Anzahl an Clients betrifft. Möchten Sie fortfahren?.
        /// </summary>
        internal static string WarningFileAbove5MiB {
            get {
                return ResourceManager.GetString("WarningFileAbove5MiB", resourceCulture);
            }
        }
    }
}
